### ISSUE TITLE
MapperParsingException[Root mapping definition has unsupported parameters:  [_boost : {name=boost, null_value=1.0}]]

### ISSUE THREAD

**Issue by quadrim** [ruflin/Elastica#1109]
I am getting 

> MapperParsingException[Root mapping definition has unsupported parameters:  [_boost : {name=boost, null_value=1.0}]]

 error in elasticsearch log while doing 

> SearchQuerySet().all()

 which returns empty list.

My Django verison: _1.6.5_ , Django-Haystack verison: 2.4.1

Complete stacktrace of the error is:

[2016-06-05 21:39:59,604][DEBUG][action.admin.indices.mapping.put] [MY.ELASTIC.SEARCH.IP] failed to put mappings on indices [[current_location]], type [modelresult]
MapperParsingException[Root mapping definition has unsupported parameters:  [_boost : {name=boost, null_value=1.0}]]
	at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:171)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:159)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:508)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by quadrim** [comment]
Created the issue in wrong repository. Sorry Folks! :)
