### ISSUE TITLE
Exception: No handler for type [string] declared on field [transaction]

### ISSUE THREAD

**Issue by spellord** [ruflin/Elastica#1495]
Hi dears,

I have this error when I try persist a entity in elastic 6

I run:
./bin/cake elastic_mapping Planillapagos

I get this error:

Exception: No handler for type [string] declared on field [transaction] in [/var/www/apps/hbc/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php, line 174]
2018-05-11 00:36:48 Error: [Elastica\Exception\ResponseException] No handler for type [string] declared on field [transaction] in /var/www/apps/hbc/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php on line 174
Stack Trace:
#0 /var/www/apps/hbc/vendor/ruflin/elastica/lib/Elastica/Request.php(171): Elastica\Transport\Http->exec(Object(Elastica\Request), Array)
#1 /var/www/apps/hbc/vendor/ruflin/elastica/lib/Elastica/Client.php(662): Elastica\Request->send()
#2 /var/www/apps/hbc/vendor/ruflin/elastica/lib/Elastica/Index.php(518): Elastica\Client->request('audit-logs/plan...', 'PUT', Array, Array)
#3 /var/www/apps/hbc/vendor/ruflin/elastica/lib/Elastica/Type.php(519): Elastica\Index->request('audit-logs/plan...', 'PUT', Array, Array)
#4 /var/www/apps/hbc/vendor/ruflin/elastica/lib/Elastica/Type/Mapping.php(272): Elastica\Type->request('planillapagos/_...', 'PUT', Array, Array)
#5 /var/www/apps/hbc/vendor/lorenzo/audit-stash/src/Shell/ElasticMappingShell.php(113): Elastica\Type\Mapping->send()
#6 /var/www/apps/hbc/vendor/cakephp/cakephp/src/Console/Shell.php(507): AuditStash\Shell\ElasticMappingShell->main(Object(App\Model\Table\PlanillapagosTable))
#7 /var/www/apps/hbc/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(230): Cake\Console\Shell->runCommand(Array, true, Array)
#8 /var/www/apps/hbc/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#9 /var/www/apps/hbc/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#10 /var/www/apps/hbc/bin/cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#11 {main}

My Dev environment is:
Php 7
Cakephp 3.4
Elasticsearch 6 (Audit Log)
Mysql 5.7.22 (Storage all Model Entities)
Ubuntu 16.04 lts

**Comment by spellord** [comment]
The problem is with lorenzo plugin:
 /var/www/apps/hbc/vendor/lorenzo/audit-stash/src/Shell/ElasticMappingShell.php(113)

String type is deprecate I change to text but now I get this error
Exception: Could not convert [transaction.index] to boolean in [/var/www/apps/hbc/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php, line 174]

**Comment by spellord** [comment]
values not_analyzed and analyzed are not long in used, instead you need use true or false values, I found other error but I see the problems is with the other plugin not with this
