### ISSUE TITLE
slash / is escaped with two slashes instead of one, parse failure

### ISSUE THREAD

**Issue by maxgalbu** [ruflin/Elastica#660]
I'm using:
- elasticsearch 1.3.1
- elastica (master branch)

My fix is to escape with one \ instead of \\

``` php
$result = str_replace('/', '\\/', $result);
```

I had a look at previous issues but i can't see why it was escaped two times.

here's the log

```
[2014-08-06 10:16:25,587][DEBUG][action.search.type       ] [Stanley Stewart] [fai][3], node[3obbmGZQS-S8hZ9twBLROg], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@50021d3]
org.elasticsearch.search.SearchParseException: [fai][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"gioved\u00ec 3\\\\/7 a","default_operator":"OR"}},"filter":{"or":[{"term":{"tipo":"pagina"}},{"term":{"tipo":"evento"}}]},"highlight":{"pre_tags":["<b>"],"post_tags":["</b>"],"fields":{"nome":{"fragment_size":300,"number_of_fragments":1},"nome_ita":{"fragment_size":300,"number_of_fragments":1},"nome_eng":{"fragment_size":300,"number_of_fragments":1},"testo_ita":{"fragment_size":300,"number_of_fragments":1},"testo_eng":{"fragment_size":300,"number_of_fragments":1}}}}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:664)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:515)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:487)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:256)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:206)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:203)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.query.QueryParsingException: [fai] Failed to parse query [giovedì 3\\/7 a]
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:240)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:238)
        at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:342)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:268)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:263)
        at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:648)
        ... 9 more
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'giovedì 3\\/7 a': Lexical error at line 1, column 16.  Encountered: <EOF> after : "/7 a"
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:130)
        at org.apache.lucene.queryparser.classic.MapperQueryParser.parse(MapperQueryParser.java:882)
        at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:223)
        ... 15 more
Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 16.  Encountered: <EOF> after : "/7 a"
        at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1133)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_scan_token(QueryParser.java:599)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3R_2(QueryParser.java:482)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_3_1(QueryParser.java:489)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_2_1(QueryParser.java:475)
        at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:226)
        at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:212)
        at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:170)
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:120)
        ... 17 more
```

**Comment by Tobion** [comment]
@kostiklv good job
